Fixing issue with event picking job:
2024-03-18 11:08:51,080 panda.log.event_picker: ERROR    Got exception <class 'TypeError'>:'tuple' object does not support item assignment Traceback (most recent call last):
  File "/opt/panda/lib/python3.11/site-packages/pandaserver/dataservice/event_picker.py", line 248, in run
    tmp_ret = self.pd2p.register_dataset_container_with_datasets(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/panda/lib/python3.11/site-packages/pandaserver/dataservice/dyn_data_distributer.py", line 435, in register_dataset_container_with_datasets
    n_files_per_dataset[0] = 1
    ~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'tuple' object does not support item assignment